#!/bin/bash -e

options=$(getopt -n cf-dns -o hqc::g::t::v:: --long help,quiet,credentials::,get::,type::,value:: -- "$@")

# '-n' replacing file name in case of an error
# '-o' stands for options (short options - only one char)
#option with ':' means that after it -must- come an argument, '::' means that -should- come an argumet, and without ':' is just a flag like help or quiet
#--long stands for long options
#what comes after '--' is the argumets to parse by getopt

exitStatus=0


#echo "$options"
eval set -- "$options"
G_FLAG=false
T_FLAG=false
V_FLAG=false
C_FLAG=false

HELP="this is help description for cf-dns script."
QUIET=false
MAIL=""
APIKEY=""
SUBDOMAIN=""
TYPE=""
VALUE=""
arg=""



while true; do
    case "$1" in

    -h | --help )
        echo "$HELP" 
        ;;

    -q | --quiet )
		#not working
        QUIET=true
		exec 2>/dev/null
        ;;

    -g | --get )
		G_FLAG=true
        SUBDOMAIN="${2}"
		shift
        ;;

    -t | --type )
		T_FLAG=true
        TYPE="${2}"
		shift
        ;;

    -v | --value )
		V_FLAG=true
        VALUE="${2}"
		shift
        ;;

    -c | --credentials )

		echo "$2"
		C_FLAG=true
		arg="${2}"
		MAIL="${arg%:*}"
		APIKEY="${arg#*:}"
		echo "$MAIL"
		echo "$APIKEY"
		if [[ ! $MAIL =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$ ]]; then 
			echo "mail address in not valid." 1>&2
		fi

		if [[ ! $APIKEY =~ ^[a-z0-9_-]+$ ]]; then 
			echo "API KEY is not valid." 1>&2
		fi
		shift
        ;;

    --)

        shift
        break
        ;;
    esac

    shift
done

if [ -z "$SUBDOMAIN" -a $G_FLAG = true ]; then 
	echo "missing subdomain argument" 1>&2
	exit 1
fi
#******************
if [ -z "$TYPE" -a $T_FLAG = true ]; then 
	echo "missing type argument" 1>&2
	exit 1
fi
#******************
if [ -z "$VALUE" -a $V_FLAG = true ]; then 
	echo "missing value argument" 1>&2
	exit 1
fi
#******************
if [ -z "$arg" -a $C_FLAG = true ]; then 
	echo "missing cardentials argument" 1>&2
	exit 1
fi

echo "${SUBDOMAIN}"
echo "${TYPE}"
echo "${QUIET}"
echo "${MAIL}"
echo "${APIKEY}"



if [ \( -n "${SUBDOMAIN}" \) -a \( -n "${TYPE}" \) ]; then
	host "${SUBDOMAIN}" >/dev/null
	if [ "$?" -eq 0 ]; then
		host "${SUBDOMAIN}" | awk '{print $4}'
	else
		echo "cf-dns: DNS entry not found">&2
		exit 1
	fi
fi 















