#!/bin/bash -e

options=$(getopt -n cf-dns -o hqc:g:t:v: --long help,quiet,credentials:,get:,type:,value: -- "$@")

# '-n' replacing file name in case of an error
# '-o' stands for options (short options - only one char)
#option with ':' means that after it -must- come an argument, '::' means that -should- come an argumet, and without ':' is just a flag like help or quiet
#--long stands for long options
#what comes after '--' is the argumets to parse by getopt

exitStatus=0


#echo "$options"
eval set -- "$options"
G_FLAG=false
T_FLAG=false
V_FLAG=false
C_FLAG=false

arr=("A" "AAAA" "CNAME" "TXT" "SRV" "LOC" "MX" "NS" "SPF")
HELP="this is help description for cf-dns script."
QUIET=false
MAIL=""
APIKEY=""
SUBDOMAIN=""
TYPE=""
VALUE=""
arg="$CF_CREDENTIALS"



while true; do
    case "$1" in

    -h | --help )
        echo "$HELP" 
		exit 1
        ;;

    -q | --quiet )
		#not working
        QUIET=true
		exec 2>/dev/null
        ;;

    -g | --get )
		G_FLAG=true
        SUBDOMAIN="${2}"
		if [[ ! $SUBDOMAIN =~ ^[a-z]++."tk"$ ]]; then
  			echo "SubDomain name is not look valid." 1>&2
			exit 1
		fi
		shift
        ;;

    -t | --type )
		
		T_FLAG=true
        TYPE="${2}"
		if [[ $TYPE =~ ^[a-z_-]+$ ]]; then	
			TYPE=$(echo $TYPE | tr [a-z] [A-Z])
			if [[ ! " ${arr[*]} " == *" $TYPE "* ]]; then
				echo "$TYPE"
				echo "type is not valid according the CloudFlare API." 1>&2  
				exit 1
			fi     
		fi
		shift
        ;;

    -v | --value )
		V_FLAG=true
        VALUE="${2}"
		shift
        ;;

    -c | --credentials )
		C_FLAG=true
		arg="${2}"
		MAIL="${arg%:*}"
		APIKEY="${arg#*:}"
		if [[ ! $MAIL =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$ ]]; then 
			echo "mail address in not valid." 1>&2
			exit 1
		fi

		if [[ ! $APIKEY =~ ^[a-z0-9_-]+$ ]]; then 
			echo "API KEY is not valid." 1>&2
			exit 1
		fi
		shift
        ;;

	*)
		echo "extra argument is not supported." 1>&2
		exit 1
		;;

    --)

        shift
        break
        ;;

    esac
    shift
done

if [ "$C_FLAG" = false ]; then #checking
	MAIL="${arg%:*}"
	APIKEY="${arg#*:}"
fi

if [ -z "$SUBDOMAIN" -a $G_FLAG = true ]; then 
	echo "missing subdomain argument" 1>&2
	exit 1
fi
#******************
if [ -z "$TYPE" -a $T_FLAG = true ]; then 
	echo "missing type argument" 1>&2
	exit 1
fi
#******************
if [ -z "$VALUE" -a $V_FLAG = true ]; then 
	echo "missing value argument" 1>&2
	exit 1
fi
#******************
if [ -z "$arg" -a $C_FLAG = true ]; then 
	echo "missing cardentials argument" 1>&2
	exit 1
fi

#echo "${SUBDOMAIN}"
#echo "${TYPE}"
#echo "${QUIET}"
#echo "${MAIL}"
#echo "${APIKEY}"



if [ \( -n "${SUBDOMAIN}" \) -a \( -n "${TYPE}" \) ]; then
	host "${SUBDOMAIN}" >/dev/null
	if [ "$?" -eq 0 ]; then
		host "${SUBDOMAIN}" | awk '{print $4}'
	else
		echo "cf-dns: DNS entry not found">&2
		exit 1
	fi
fi 















