#!/bin/bash

# -sb is for remove background content
# you can use command sed 's/\"//g' for remove "" from the output




key="5699e0373a39ca57bc71df243c562e8a07a3a"
mail="tapirotamirsh@gmail.com"
zoneID=$(./getZoneId "$mail" "$key")
#echo "$zoneID"

curl -sb -X GET "https://api.cloudflare.com/client/v4/zones/$1/dns_records" \
     -H "X-Auth-Email: $2" \
     -H "X-Auth-Key: $3" \
     -H "Content-Type: application/json" | jq .result[] | sed 's/\"//g'

