#!/bin/bash -e

# -sb is for remove background content
# you can use command sed 's/\"//g' for remove "" from the output




zoneID=$(./getZoneId)

mail="tapirotamirsh@gmail.com"
key="5699e0373a39ca57bc71df243c562e8a07a3a"

curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${zoneID}/dns_records" \
     -H "X-Auth-Email: ${mail}" \
     -H "X-Auth-Key: ${key}" \
     -H "Content-Type: application/json"
