#!/bin/bash -e


mail="tapirotamirsh@gmail.com"
key="5699e0373a39ca57bc71df243c562e8a07a3a"
TYPE="A"

curl -X PUT "https://api.cloudflare.com/client/v4/zones/1c85e57e85ae11f07ba2aeb951fe47fc/dns_records/1d6b6b33369b0cb12f934312d97dc7fa" \
     -H "X-Auth-Email: ${mail}" \
     -H "X-Auth-Key: ${key}" \
     -H "Content-Type: application/json" \
     --data '{"type":"'${TYPE}'","name":"www.testsce.tk","content":"'${1}'"}' | jq

