#!/bin/bash -e

#-sb is for removing the extra content
#get zone ID



MAIL="tapirotamirsh@gmail.com"
KEY="5699e0373a39ca57bc71df243c562e8a07a3a"

curl -sb -X GET "https://api.cloudflare.com/client/v4/zones"		-H "X-Auth-Email: tapirotamirsh@gmail.com"		-H "X-Auth-Key: 5699e0373a39ca57bc71df243c562e8a07a3a"		-H "Content-Type: application/json"	| jq .result[0].id | sed 's/\"//g'
