#!/bin/bash -e

#-sb is for removing the extra content
#get zone ID



MAIL="$1"
KEY="$2"

curl -sb -X GET "https://api.cloudflare.com/client/v4/zones"		-H "X-Auth-Email: ${MAIL}"		-H "X-Auth-Key: ${KEY}"		-H "Content-Type: application/json"	| jq '.result[0].id' 2> /dev/null | sed 's/\"//g'
